server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://124.222.34.143:3306/science_forum?serverTimezone=GMT
    username: root
    password: JLLwcl123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      host: "124.222.34.143"
      port: 27017
      database: "science_forum"
      username: "forum"
      password: "password"
  redis:
    port: 6379
    host: 124.222.34.143
    database: 0

logging:
  config: classpath:log4j2.xml
